# Generated by Django 4.0.5 on 2022-06-24 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0002_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_name',
            new_name='productname',
        ),
    ]
