# Generated by Django 4.0.5 on 2022-06-24 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0003_rename_product_name_products_productname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Categoryname',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Categoryname',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='price',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='productname',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='quantity',
            new_name='Quantity',
        ),
    ]
